'use client';

import { use, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { usePoll, useAction } from '@/lib/hooks';
import { formatBytes, timeAgo } from '@/lib/format';
import {
  Badge, Button, Card, ErrorNote, Mono, SectionTitle,
  Spinner, StatusPill, TextArea,
} from '@/components/ui';
import { TaskBoard } from '@/components/panels/TaskBoard';
import { MemoryExplorer } from '@/components/panels/MemoryExplorer';
import { MessageFeed } from '@/components/panels/MessageFeed';
import { DataFlowMap } from '@/components/viz/DataFlowMap';
import { PipelineStrip } from '@/components/viz/WorkflowPipeline';

type Tab = 'overview' | 'tasks' | 'memory' | 'messages' | 'flow';

/**
 * Everything the platform knows and is doing about one codebase.
 *
 * Tabbed rather than one long scroll: these are four genuinely different
 * questions (what is this codebase / what is being done to it / what have we
 * learned / what are the agents saying), and stacking them would bury the last
 * two below a very long fold.
 */
export default function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [tab, setTab] = useState<Tab>('overview');

  const project = usePoll(() => api.getProject(id), 8000, [id]);
  const tasks = usePoll(() => api.listTasks(id), 4000, [id]);
  const memory = usePoll(() => api.memory(id), 10_000, [id]);
  const messages = usePoll(() => api.messages(id), 5000, [id]);
  const runs = usePoll(() => api.listRuns(id), 5000, [id]);

  const reanalyze = useAction(api.reanalyze);

  if (project.error) return <ErrorNote message={project.error} onRetry={project.refresh} />;
  if (!project.data) return <Spinner label="Loading project" />;

  const p = project.data.project;
  const repo = project.data.repository;

  const TABS: { id: Tab; label: string; count?: number }[] = [
    { id: 'overview', label: 'Overview' },
    { id: 'tasks', label: 'Tasks', count: tasks.data?.count },
    { id: 'memory', label: 'Memory', count: memory.data?.knowledge.length },
    { id: 'messages', label: 'Messages', count: messages.data?.count },
    { id: 'flow', label: 'Data flow' },
  ];

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Link href="/projects" className="text-xs text-[var(--text-muted)] hover:underline">
              Projects
            </Link>
            <span aria-hidden className="text-xs text-[var(--text-muted)]">/</span>
            <h1 className="truncate text-lg font-semibold tracking-tight">{p.name}</h1>
            <StatusPill status={p.status === 'ready' ? 'done' : p.status} size="xs" />
          </div>
          <p className="mt-0.5 text-xs text-[var(--text-muted)]">
            {p.profile.fileCount} files indexed · {formatBytes(p.profile.totalBytes)}
            {p.lastAnalyzedAt && ` · analysed ${timeAgo(p.lastAnalyzedAt)}`}
            {repo && ` · ${repo.currentBranch}@${repo.headCommit?.slice(0, 7) ?? '—'}`}
          </p>
        </div>
        <Button
          size="sm"
          disabled={reanalyze.pending}
          onClick={async () => {
            await reanalyze.execute(id);
            project.refresh();
            memory.refresh();
          }}
          title="Re-index the checkout and refresh the detected profile"
        >
          {reanalyze.pending ? 'Re-analysing…' : '↻ Re-analyse'}
        </Button>
      </div>

      <div className="flex gap-1 border-b">
        {TABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`-mb-px border-b-2 px-3 py-1.5 text-xs transition-colors ${
              tab === t.id
                ? 'border-[var(--series-1)] font-medium text-[var(--text-primary)]'
                : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
            }`}
          >
            {t.label}
            {t.count !== undefined && t.count > 0 && (
              <span className="tabular ml-1.5 rounded-full bg-[var(--surface-2)] px-1.5 text-[10px]">
                {t.count}
              </span>
            )}
          </button>
        ))}
      </div>

      {tab === 'overview' && (
        <div className="grid gap-5 lg:grid-cols-2">
          <Card>
            <SectionTitle
              title="Detected profile"
              hint="Generated by static analysis at onboarding. This is injected into every agent's system prompt."
            />
            <dl className="space-y-2 text-xs">
              <Detail label="Languages">
                <div className="flex flex-wrap gap-1">
                  {p.profile.languages.map((l) => <Badge key={l} color="var(--series-1)">{l}</Badge>)}
                </div>
              </Detail>
              <Detail label="Frameworks">
                <div className="flex flex-wrap gap-1">
                  {p.profile.frameworks.length
                    ? p.profile.frameworks.map((f) => <Badge key={f} color="var(--series-2)">{f}</Badge>)
                    : <span className="text-[var(--text-muted)]">none detected</span>}
                </div>
              </Detail>
              <Detail label="Architecture"><span className="text-[var(--text-secondary)]">{p.profile.architecture}</span></Detail>
              <Detail label="Database"><span className="text-[var(--text-secondary)]">{p.profile.database}</span></Detail>
              <Detail label="Testing"><span className="text-[var(--text-secondary)]">{p.profile.testingFramework}</span></Detail>
              <Detail label="Deployment"><span className="text-[var(--text-secondary)]">{p.profile.deployment}</span></Detail>
              <Detail label="Build"><Mono>{p.profile.buildCommand ?? 'unknown'}</Mono></Detail>
              <Detail label="Test"><Mono>{p.profile.testCommand ?? 'unknown'}</Mono></Detail>
              <Detail label="Entry points">
                <div className="flex flex-wrap gap-1">
                  {p.profile.entryPoints.length
                    ? p.profile.entryPoints.map((e) => <Mono key={e}>{e}</Mono>)
                    : <span className="text-[var(--text-muted)]">none detected</span>}
                </div>
              </Detail>
            </dl>
          </Card>

          <div className="space-y-5">
            <Card>
              <SectionTitle
                title="Conventions the agents must follow"
                hint="Detected from config files. Agents are told to match these."
              />
              {p.profile.conventions.length ? (
                <ul className="space-y-1.5">
                  {p.profile.conventions.map((c, i) => (
                    <li key={i} className="flex gap-2 text-[11px] text-[var(--text-secondary)]">
                      <span aria-hidden style={{ color: 'var(--status-good)' }}>✓</span>
                      {c}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-[11px] text-[var(--text-muted)]">
                  No tooling config detected — agents will infer style from neighbouring files.
                </p>
              )}
            </Card>

            <StandingOrders projectId={id} initial={p.customInstructions ?? ''} onSaved={project.refresh} />

            <Card>
              <SectionTitle
                title="Recent runs"
                right={<Link href="/runs" className="text-[11px] text-[var(--series-1)] hover:underline">All →</Link>}
              />
              {!runs.data?.runs.length ? (
                <p className="text-xs text-[var(--text-muted)]">No workflow runs for this project yet.</p>
              ) : (
                <ul className="space-y-2">
                  {runs.data.runs.slice(0, 4).map((r) => (
                    <li key={r._id}>
                      <Link href={`/runs/${r._id}`} className="block rounded-lg border p-2 hover:border-[var(--border-strong)]">
                        <div className="flex items-start justify-between gap-2">
                          <p className="line-clamp-1 text-[11px] font-medium">{r.request}</p>
                          <StatusPill status={r.status} size="xs" />
                        </div>
                        <div className="mt-1.5"><PipelineStrip run={r} /></div>
                      </Link>
                    </li>
                  ))}
                </ul>
              )}
            </Card>
          </div>
        </div>
      )}

      {tab === 'tasks' && (
        <Card>
          <SectionTitle
            title="Task engine"
            hint="Every workflow step also materialises here, so it is inspectable exactly like a task you created."
          />
          {tasks.data ? <TaskBoard tasks={tasks.data.tasks} onChanged={tasks.refresh} /> : <Spinner />}
        </Card>
      )}

      {tab === 'memory' && (
        <Card>
          <SectionTitle
            title="Long-term memory"
            hint="What the organization has learned about this codebase. Retrieved into future agent runs."
          />
          {memory.data ? <MemoryExplorer memory={memory.data} /> : <Spinner />}
        </Card>
      )}

      {tab === 'messages' && (
        <Card>
          <SectionTitle title="Agent message bus" />
          {messages.data ? <MessageFeed messages={messages.data.messages} /> : <Spinner />}
        </Card>
      )}

      {tab === 'flow' && (
        <Card>
          <SectionTitle
            title="How this project's data moves"
            hint="Live counts from this project, mapped onto the platform pipeline."
          />
          <DataFlowMap
            counts={{
              files: p.profile.fileCount,
              knowledge: memory.data?.knowledge.length,
              tasks: tasks.data?.count,
              messages: messages.data?.count,
              decisions: memory.data?.decisions.length,
              runs: runs.data?.count,
            }}
          />
        </Card>
      )}
    </div>
  );
}

function Detail({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[100px_1fr] items-start gap-2">
      <dt className="text-[var(--text-muted)]">{label}</dt>
      <dd className="min-w-0">{children}</dd>
    </div>
  );
}

function StandingOrders({
  projectId,
  initial,
  onSaved,
}: {
  projectId: string;
  initial: string;
  onSaved: () => void;
}) {
  const [value, setValue] = useState(initial);
  const save = useAction(api.setInstructions);
  const dirty = value !== initial;

  return (
    <Card>
      <SectionTitle
        title="Standing orders"
        hint="Injected into every agent prompt for this project. House rules that always apply."
      />
      <TextArea
        rows={3}
        value={value}
        placeholder="e.g. Never use floating point for currency. Any change touching money needs a test asserting exact decimal amounts."
        onChange={(e) => setValue(e.target.value)}
      />
      <div className="mt-2 flex items-center justify-between gap-2">
        <span className="text-[10px] text-[var(--text-muted)]">
          {dirty ? 'Unsaved changes' : 'Applies to every agent on this project'}
        </span>
        <Button
          size="sm"
          variant={dirty ? 'primary' : 'default'}
          disabled={!dirty || save.pending}
          onClick={async () => {
            await save.execute(projectId, value);
            onSaved();
          }}
        >
          {save.pending ? 'Saving…' : 'Save'}
        </Button>
      </div>
      {save.error && (
        <p className="mt-2 text-[11px]" style={{ color: 'var(--status-critical)' }}>{save.error}</p>
      )}
    </Card>
  );
}
